### ISSUE TITLE
-

### ISSUE THREAD

**Issue by NIKJOO** [nasnet-community/neighbor-link#3]

**Comment by markpash** [comment]
Hi @NIKJOO :)))
I see you've closed this issue. Is the recommendation you gave still a valid concern?

**Comment by happynet-why** [comment]
به نظر اصل موضوع مهم میاد .البته با توجه به اینکه این ارتباط تنها در شبکه وایرلسی که خود مدیر شبکه بهش متصله میفته . اهمیت کمتری داره . اما حتما راهکاری برای اون در نظر گرفته خواهد شد

**Comment by NIKJOO** [comment]
> به نظر اصل موضوع مهم میاد .البته با توجه به اینکه این ارتباط تنها در شبکه وایرلسی که خود مدیر شبکه بهش متصله میفته . اهمیت کمتری داره . اما حتما راهکاری برای اون در نظر گرفته خواهد شد

دوست گرامی قبل از دیدن نام پشم فروشان میخواستم کمک کنم ولی با دیدن اسم ایشون به کل منصرف شدم ؛ موفق باشید.
